"""Emit RECEIPT v1.0 witness identities as Lean 4 theorems over ZMod p.

Two statement forms per witness:

  column form   For every column k in the union of the supports of
                {lam_i * R_i} and of e_t - sum_m c_m e_m, one equation
                  (sum_i lam_i * R_i[k] : ZMod p) = expect_k
                joined by conjunction and proved by `decide +kernel`.
                Trust boundary: this emitter enumerates the columns. A column
                outside that union is 0 = 0 on both sides by construction.

  linear form   forall x : N -> ZMod p,
                  sum_i lam_i * (sum_k R_i[k] * x k) = x t - sum_m c_m * x m
                proved by `ring_nf; reduce_mod_char` (twice). This is the identity
                itself as an equality of linear forms; no column enumeration is
                trusted. It is emitted only for small witnesses.

Neither form uses native_decide, implemented_by or sorry.
"""
from __future__ import annotations

import re


def _zm(v: int, p: int) -> str:
    return f"({v} : ZMod {p})"


def theorem_name(tag: str) -> str:
    return "w_" + re.sub(r"[^A-Za-z0-9_]", "_", tag)


def column_form(tag, rows, w, tactic="decide +kernel", split=True) -> str:
    """rows: list of {col: val mod p}; w: parsed Witness (second_checker.checker)."""
    p = w.p
    by_col: dict[int, list[tuple[int, int]]] = {}
    for i, li in sorted(w.lam.items()):
        for col, v in sorted(rows[i].items()):
            by_col.setdefault(col, []).append((li, v))
    expect = {w.target: "1"}
    for m, cm in sorted(w.c.items()):
        expect[m] = f"-{cm}" if m != w.target else f"1 - {cm}"
    cols = sorted(set(by_col) | set(expect))
    eqs = []
    for k in cols:
        terms = by_col.get(k, [])
        lhs = " + ".join(f"{li} * {v}" for li, v in terms) if terms else "0"
        rhs = expect.get(k, "0")
        eqs.append((f"  (({lhs} : ZMod {p}) = ({rhs} : ZMod {p}))", k))
    body = "\n".join(f"{e}{' ∧' if j < len(eqs) - 1 else ''}  -- col {k}"
                     for j, (e, k) in enumerate(eqs))
    name = theorem_name(tag)
    if not split:
        return f"theorem {name}_col :\n{body}\n    := by\n  {tactic}\n"
    # Split: one kernel-checked lemma per column, then the full conjunction
    # assembled from them (no Decidable instance search over a large And).
    lemmas = "".join(f"theorem {name}_k{j} :\n{e}  -- col {k}\n    := by {tactic}\n"
                     for j, (e, k) in enumerate(eqs))
    proof = ", ".join(f"{name}_k{j}" for j in range(len(eqs)))
    return f"{lemmas}theorem {name}_col :\n{body}\n    := ⟨{proof}⟩\n"


def linear_form(tag, rows, w) -> str:
    p = w.p
    parts = []
    for i, li in sorted(w.lam.items()):
        row = " + ".join(f"{v} * x {col}" for col, v in sorted(rows[i].items())) or "0"
        parts.append(f"{li} * ({row})")
    lhs = " + ".join(parts) if parts else "0"
    rhs = f"x {w.target}" + "".join(f" - {cm} * x {m}" for m, cm in sorted(w.c.items()))
    return (f"theorem {theorem_name(tag)}_lin : ∀ x : ℕ → ZMod {p},\n"
            f"    {lhs} =\n    {rhs} := by\n"
            f"  intro x; ring_nf; reduce_mod_char; ring_nf; reduce_mod_char\n")


HEADER = """import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.ReduceModChar
import Mathlib.Tactic.Ring

-- Generated by second_checker.lean_emit. Each theorem states one RECEIPT v1.0
-- identity  sum_i lam[i]*R_i == e_t - sum_m c[m]*e_m  (mod p)  over ZMod p.
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option profiler true
set_option profiler.threshold 0
"""


def lean_file(blocks: list[str], names: list[str]) -> str:
    axioms = "".join(f"#print axioms {n}\n" for n in names)
    return HEADER + "\n" + "\n".join(blocks) + "\n" + axioms
